config/routes.rb
Rails.application.routes.draw do

  # Set Project Root Path #
  root 'static_pages#home'

  # Set Static Page Directories #
  get 'about',        to: 'static_pages#about'
  get 'connect',      to: 'static_pages#connect'
  get 'donate',       to: 'static_pages#donate'
  get 'devlogs',      to: 'static_pages#devlogs'

  # Set User Directories #
  get    'signup',   to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  # Set Project Resources #
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def connect
  end

  def donate
  end

  def devlogs
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="center jumbotron abt">
  <h1 class="abt_hdr">
    About Binary Deck
  </h1>
  <p class="abt_txt">
    Binary Deck is designed &amp; created by Dr. Aubrey W. Love II (AKA B10 H4ck3r).<br/>
    <br/>
    <b><i><u>Why create Binary Deck?</u></i></b><br/>
    Binary Deck was originally created in order to showcase Aubrey's programming
    abilities. However, as several of his friends pointed out, there is no
    true Anonymous Social Media website in which would ensure their safety
    and security while socializing with their friends. So Aubrey designed it
    in order to fulfill his friends desires.<br/>
    <br/>
    <b><i><u>What Keeps Me Safe?</u></i></b><br/>
    <br/>
    Our abilities to not read your stored cache cookies is a start. We do not
    care what you are searching for, nor have any requests to shove ads in your
    face like our competitors. We are not concerning ourselves with your online
    presence time. And we are also anonymizing your IP address. Your real IP Address
    will be displayed on your profile "Deck" alongside with your Fake IP Address.<br/>
    <br/>
    <b><i><u>How do you collect Funds?</u></i></b><br/>
    <br/>
    Our funding process, as of 01/01/2021, Aubrey is the sole supporter and financial
    backer of this operation. However, we are also accepting donations from other
    individuals and organizations. All donations will be used strictly for the
    future development of Cyber Deck and new resources we can utilize to help
    make this site even better and keep it up.<br/>
    <br/>
    <b><i><u>How much does this cost?</u></i></b><br/>
    <br/>
    The development cost break down sheet for Cyber Deck is as follows;<br/>
    * Hosting ~ $25 Monthly<br/>
    * Domain ~ $30 Yearly<br/>
    * Internet ~ $75 Monthly<br/>
    * Electricity ~ $50 Monthly<br/>
    * Time ~ $13 Hourly<br/>
    Total Yearly Cost: $26,790!<br/>
    Granted, the majority of the funds is with Time for Developer, but as you can see,
    just the basic fundamentals of designing, developing, and hosting this website
    is extremely expensive. So donations are greatly appreciated. <br/>
    <br/>
    <b><i><u>Why do I see ads?</u></i></b><br/>
    <br/>
    While we do not actively collect your cache and store it for customized ad placement,
    we have taken Google Ads and integrated them into the website for assistance on financial
    stability. The ads are located in very selected spots throughout the website,
    in which are visible, but not actively being pushed directly into your feed directly.
    Thus granting you the ability to see your friends posts and activities without
    scrolling throughout several ads that do not apply to you. Instead we place them
    on different aspects of our site just to show them, but not actively shove them
    in your face like our competitors. <br/>
    <br/>
    <b><i><u>What trackers are you using?</u></i></b><br/>
    <br/>
    We are primarly using Google Tracking only to monitor where are users are coming
    from. We are not storing any active information from you directly. You will
    see your IP Address on your profile page, however, that is active collecting and
    not storing anything. We are using Google Tracking, not to store any information,
    but to gather a monthly report on discovering where are most active users are located
    at in order to provide new resources for the development of Cyber Deck to
    cater to our broad range of users.<br/>
</div>

app/views/static_pages/connect.html.erb
<% provide(:title, "Connect") %>
<div class="center jumbotron cnt">
  <h1 class="cnt_hdr">
    Connect with the developer!
  </h1><br/>
  <br/>
  <p class="cnt_txt">
    I am greatly appreciated that you are wanting to connect with me. Regardless
    if you are wanting to know more about the development process of Cyber Deck,
    eager to discover the next release date and update information, or virtually
    any other reason, I am happy to have a new connection!<br/>
    For those who are still on other social media platforms;<br/>
    <br/>
    <a href="https://www.facebook.com/b10h4ck3r" target="_blank"><i class="fab fa-facebook-f fa_ico"></i></a>
    <a href="https://www.linkedin.com/in/dr-aubrey-love-ii-0051b1202" target="_blank"><i class="fab fa-linkedin-in fa_ico"></i></a>
    <a href="https://www.twitter.com/H4ck3rB10" target="_blank"><i class="fab fa-twitter fa_ico"></i></a>
    <a href="https://www.github.com/B10-H4ck3r" target="_blank"><i class="fab fa-github fa_ico"></i></a>
</div>

app/views/static_pages/devlogs.html.erb
<% provide(:title, "DevLogs") %>
<div class="center jumbotron dvlg">
  <h1 class="dev_hdr">
    Cyber Deck DevLogs
  </h1>
  <p class="dev_txt">
    Want to discover what we have done to Cyber Deck so far? No problem!<br/>
    From this page, one is fully able to discover every single time we have
    pushed an update and the exact Date/Time/Reason!<br/>
  </p>
  <p class="dev_log_hdr">
    01/01/2021 @ 16:20
  </p>
  <p class="dev_log_txt">
    * Create Basic Landing Pages<br/>
    * Integrated Bootstrap<br/>
    * Converted Pages to Dynamic Pages<br/>
    * Structured Project Routes<br/>
  </p>
  <p class="dev_log_hdr">
    01/02/2021 @ 13:20
  </p>
  <p class="dev_log_txt">
    * Setup Heroku Development Server<br/>
    * Designed General Theme<br/>
  </p>
  <p class="dev_log_hdr">
    01/02/2021 @ 14:40
  </p>
  <p class="dev_log_txt">
    * Add SSL to Heroku Deployment<br/>
    * Setup Google Tracking<br/>
    * Setup Google Ads<br/>
  </p>
  <p class="dev_log_hdr">
    01/02/2021 @ 15:30
  </p>
  <p class="dev_log_txt">
    * Integrated Font-Awesome<br/>
    * Added Content to Landing Pages<br/>
  </p>
  <p class="dev_log_hdr">
    01/02/2021 @ 15:40
  </p>
  <p class="dev_log_txt">
    * Finished All Landing Pages<br/>
    * Added Donation Options<br/>
    * Finished GUI Theme<br/>
  </p>
  <p class="dev_log_hdr">
    01/03/2021 @ 12:30
  </p>
  <p class="dev_log_txt">
    * Created User Registration<br/>
  </p>
  <p class="dev_log_hdr">
    01/03/2021 @ 13:00
  </p>
  <p class="dev_log_txt">
    * Created the Login Process
  </p>
  <p class="dev_log_hdr">
    01/03/2021 @ 14:50
  </p>
  <p class="dev_log_txt">
    * Edit Profile Page Created<br/>
    * Show All Users<br/>
    * Created Admin Attribute<br/>
    * Included Pagination<br/>
    * Allowed Deletion of Users<br/>
  </p>
  <p class="dev_log_hdr">
    01/03/20210 @ 15:05
  </p>
  <p class="dev_log_txt">
    * Fixed Log In Issue
  </p>
  <p class="dev_log_hdr">
    01/03/2021 @ 18:30
  </p>
  <p class="dev_log_txt">
    * Started on Profile GUI Theme<br/>
    * Fixed Edit Profile Page
  </p>
  <p class="dev_log_hdr">
    01/04/2021 @ 07:20
  </p>
  <p class="dev_log_txt">
    * Fixed Load Image Error on Heroku
  </p>
  <p class="dev_log_hdr">
    01/04/2021 @ 18:10
  </p>
  <p class="dev_log_txt">
    * Included Post Creation<br/>
    * Setup Feed Structure<br/>
    * Integrated AWS for Active Storage
  </p>
  <p class="dev_log_hdr">
    01/04/2021 @ 19:20
  </p>
  <p class="dev_log_txt">
    * Start working on User Profile Theme
  </p>
  <p class="dev_log_hdr">
    01/05/2021 @ 08:50
  </p>
  <p class="dev_log_txt">
    * Added Follow Users
  </p>
  <p class="dev_log_hdr">
    01/05/2021 @ 12:20
  </p>
  <p class="dev_log_txt">
    * Added Avatar Uploads<br/>
    * Added Banner Uploads
  </p>
  <p class="dev_log_hdr">
    01/05/2021 @ 14:00
  </p>
  <p class="dev_log_txt">
    * Added a few GUI Designs<br/>
    * Updated View Users Page
  </p>
</div>

app/views/static_pages/donate.html.erb
<% provide(:title, "Donate") %>
<div class="center jumbotron dnt">
  <h1 class="dnt_hdr">
    Donate to Cyber Deck
  </h1>
  <p class="dnt_txt">
    Your contributions to Cyber Deck are most appreciated. And that is an understatement!<br/>
    The developer is constantly working hard to ensure the safety and anonymity of a new
    online social media experience. And while this is just one of the tasks he is working on,
    it is most certianly his most favorite one. <br/>
    <br/>
    Your donation does more than just give the developer money and use that as a tax right off.
    But rather instead, you are encouraging a developer to do more, learn more, go further, and
    bring him hope of a better social media experience!<br/>
    <br/>
    While there are several methods you can use to donate to your desired charity, we have setup
    the following methods to accept donations at this time. Please note, the donation options
    may change in time, and we may include more methods to donate as well.<br/>
    <br/>
    <table border="0" align="center">
      <tr>
        <td>
          <%= image_tag('paypal.png', class: "dnt_img") %>
        </td>
        <td>
          <%= image_tag('cashapp1.png', class: "dnt_img") %>
        </td>
        <td>
          <%= image_tag('bitcoin1.png', class: "dnt_img") %>
        </td>
      </tr>
      <tr>
        <td><br/>
          <%= link_to "PayPal", "paypal.me/b10h4ck3r", target: "_blank", class: "dnt_lnk" %>
        </td>
        <td><br/>
          <%= link_to "CashApp", "https://cash.app/$B10H4ck3r", target: "_blank", class: "dnt_lnk" %>
        </td>
        <td><br/>
          <%= link_to "Bitcoin", "https://blockchair.com/bitcoin/address/bc1qrua8yzvkv2eg9njx5d9zhvdzymd8nvgntckh5j", target: "_blank", class: "dnt_lnk" %>
        </td>
      </tr>
    </table>
</div>

app/views/static_pages/home.html.erb
<div class="center jumbotron hme">
  <h1 class="wlcm_hdr">Welcome to the CyberDeck</h1>

  <h2 class="wlcm_txt">
    Safe Secure Online Social Media Anonymous Experience!<br/>
    Connect with all of your friends in one safe online social
    media experience with ease!<br/>
    <br/>
    What's Included with your account;<br/>
    IP Address NOT being stored!<br/>
    Fake IP Address!<br/>
    Connection to Friends!<br/>
    + More!<br/>
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>&nbsp;&nbsp;&nbsp;<%= link_to "Login!", login_path, class: "btn btn-lg btn-success" %>
</div>