config/routes.rb
Rails.application.routes.draw do

  # Set Project Root Path #
  root 'static_pages#home'

  # Set Static Page Directories #
  get 'about',        to: 'static_pages#about'
  get 'connect',      to: 'static_pages#connect'
  get 'donate',       to: 'static_pages#donate'
  get 'devlogs',      to: 'static_pages#devlogs'

  # Set User Directories #
  get    'signup',   to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  # Set Project Resources #
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/7bed33201a.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Audiowide&family=Big+Shoulders+Stencil+Text&family=Black+Ops+One&family=Cinzel&family=Cinzel+Decorative&family=Goldman&family=Merriweather:ital@1&family=Orbitron&family=Playfair+Display+SC&family=Righteous&family=Source+Code+Pro&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script data-ad-client="ca-pub-3798545509082542" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-MCV9Y77M3N"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-MCV9Y77M3N');
    </script>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse" style="background-color: gray">
      <div class="container">
        <%= link_to "CyberDeck", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li id="mnu_itm"><%= link_to "Home",   root_path %></li>
            <li class="dropdown" id="mnu_itm">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Discover <b class="caret"></b>
              <ul class="dropdown-menu" style="background-color: darkgray;">
                <li id="mnu_itm_drp"><%= link_to "About", about_path %></li>
                <li id="mnu_itm_drp"><%= link_to "Connect", connect_path %></li>
                <li id="mnu_itm_drp"><%= link_to "Dev Logs", devlogs_path %></li>
                <li id="mnu_itm_drp"><%= link_to "Donate",   donate_path %></li>
              </ul>
            </li>
            <% if logged_in? %>
              <li class="dropdown" id="mnu_itm">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" style="background-color: darkgray;">
                  <li id="mnu_itm_drp"><%= link_to "My Profile", current_user %></li>
                  <li id="mnu_itm_drp"><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li id="mnu_itm_drp">
                    <%= link_to "Log out", logout_path, method: :delete %>
                  </li>
                  <li class="divider"></li>
                  <li id="mnu_itm_drp"><%= link_to "Users", users_path %></li>
                </ul>
              </li>
            <% else %>
              <li id="mnu_itm"><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>